---
- hosts: all
  become: true
  pre-tasks:

  - name: install apache2amd php packages in Ubuntu and CentOS
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
- hosts: fileserver
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
